Redirect to story url
parameter1/fortnight-web pull request #1
Opened 2021-04-15 22:00 UTC by solocommand

When visiting a story on the react app, check the published story's URL. If it does not match (and we're not in a development environment) redirect to the expected url. On dev, emit a notice about the expected redirect.

In practice:
When visiting http://localhost:3005/story/test-advertiser/test/5df94374466a9400015d4862 the developer will be warned (via the terminal or browser console, depending on whether the navigation was server- or client-side, respectively) that the redirect was aborted.

When visiting https://example.stories.native-x.parameter1.com and clicking on the test story, the browser will redirect (client-side) to the expected story url.

When visiting https://example.stories.native-x.parameter1.com/story/test-advertiser/test/5df94374466a9400015d4862, the browser will receive a 301 to the expected story url (https://www.test.com/sponsored/5df94374466a9400015d4862).

2021-04-15 22:01 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Embed Native-X stories within the site](https://trello.com/c/rHbOMWJt/48-embed-native-x-stories-within-the-site)

2021-04-15 22:27 UTC, zarathustra323 requested changes

2021-04-15 22:27 UTC, zarathustra323 commented on src/pages/story.jsx
> +        if (requestUrl.includes('localhost')) {
Can this an environment variable instead of the host name?

2021-04-16 14:51 UTC, zarathustra323 approved these changes

2021-04-16 14:52 UTC, merged